### ISSUE TITLE
[Proposal For Puppy Coin Dao] Puppy coin distribution for everyone in the world.

### ISSUE THREAD

**Issue by Miahelloworld** [MarvinJanssen/executor-dao#1]
Puppy Coin

Puppy coin is a cryptocurrency for everyone in the world. Can we run a DAO on executor-dao for Puppy Coin?  How can we run this distribution fairly and transparently? @MarvinJanssen

**How to distribute the puppy coin?**

* Each person can get 100 free puppy coin in one month via smart contract.

* Each person can get no more than 1200 free puppy coin in one year.

* From 18 years old, every year, each person will get 1200 puppy coin in the next 82 years

* Each person can get free puppy coin no more than 98400.

* Only 8 billion people can get the free puppy coin.

* The puppy coin will be issued on different blockchain.

* The gas fees(transaction fees) on distribution only come from donation.

* No ico, no pre-sale, no venture capitals.

* Each person must get through the KYC and video verification, or verified by everyone's biometric passport.

* Only the DAO has full control over the minting, burning, transferring, and locking.

**FAQ**

**If there is no donation, how can I get the free puppy coin?**

To keep everyone follow the rule, we have to use the donation to pay for the gas fees. If there is no donation, there will no new token distribution.

**Does this puppy coin has any value?**

Please note, this cryptocurrency project only for a society experiment, anyone should not invest their fiat money on this crypto! We also recommend that you can use it for your daily life.

**Why should this coin has these rules? What is the purpose for this puppy coin?**

Let everyone on the earth use the crypto in their daily life, no worry about the inflation.

**If I was already 58 years old, how many coins can I get?**

If your birthday is Jun 12, 1964. After your identity get verified, Let's assume your identity get through on April 10, 2022. From April 12, 2022, Your own wallet will get 100 puppy coin in every month, On Jun 12, 2064, you will receive the last 100 free puppy coin in that day. Since Jun 12, 2064, you will no more receive the free puppy coin.

**Who can decide the token distribution?**

A decentralized organization run this society experiment. After each user get verified, The token distribution will based on the smart contract.

**Comment by MarvinJanssen** [comment]
Closing because I do not think this issue tracker is the right place to post the above. I suggest to join the Stacks Discord server if you want to explore how you could possibly build and launch your project. (Sounds like quite the challenge, though.)
